# Emotion Detection System using Natural Language Processing (NLP)

Text Preprocessing Pipeline
Raw text ko clean kiya (lowercase, stopwords removal, punctuation removal)

Tokenization & Vectorization
Text ko numerical format me convert kiya using techniques like Tokenizer / TF-IDF

Deep Learning Model
Neural Network (Dense / LSTM) use karke emotion classify kiya
Multi-Class Emotion Classification
Multiple emotions detect karta hai jaise:
👉 Happy, Sad, Angry, Excited, etc.
Accurate Prediction System
Model trained hai taaki unseen text pe bhi correct emotion predict kare
Real-Time Input Testing
User apna text input dekar instantly emotion check kar sakta hai
Efficient Training Pipeline
Small dataset pe bhi optimized training (epochs, batch size tuning)
End-to-End NLP Workflow
Data preprocessing → training → prediction sab ek pipeline me

In [2]:
import pandas as pd
import numpy as np
import nltk
import re
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
# data = {
#     "text": [
#         "I am very happy today",
#         "This is amazing",
#         "I feel great",
#         "I am so excited",
#         "I am sad",
#         "This is depressing",
#         "I feel bad",
#         "I am unhappy",
#         "I am angry",
#         "This makes me mad",
#         "I am frustrated",
#         "I hate this"
#     ],
#     "emotion": [
#         "happy", "happy", "happy", "happy",
#         "sad", "sad", "sad", "sad",
#         "angry", "angry", "angry", "angry"
#     ]
# }

data = {
    "text": [
        # 😊 Happy
        "I am feeling very happy today",
        "This is such a wonderful day",
        "I feel joyful and excited",
        "Life is beautiful",
        
        # 😢 Sad
        "I feel very sad",
        "This is depressing",
        "I am heartbroken",
        "I feel lonely and down",
        
        # 😡 Angry
        "I am very angry right now",
        "This makes me mad",
        "I am frustrated",
        "I hate this situation",
        
        # 😨 Fear
        "I am scared of this",
        "This is terrifying",
        "I feel nervous",
        "I am afraid of what will happen",
        
        # 😲 Surprise
        "Wow this is surprising",
        "I did not expect this",
        "This shocked me",
        "I am amazed",
        
        # 🤢 Disgust
        "This is disgusting",
        "I feel sick seeing this",
        "This is gross",
        "I hate this smell",
        
        # 😍 Love
        "I love you so much",
        "This is lovely",
        "I feel so attached",
        "You mean everything to me",
        
        # 😌 Calm
        "I feel relaxed",
        "This is peaceful",
        "I am calm and quiet",
        "I feel at ease"
    ],
    
    "emotion": [
        "happy","happy","happy","happy",
        "sad","sad","sad","sad",
        "angry","angry","angry","angry",
        "fear","fear","fear","fear",
        "surprise","surprise","surprise","surprise",
        "disgust","disgust","disgust","disgust",
        "love","love","love","love",
        "calm","calm","calm","calm"
    ]
}
df = pd.DataFrame(data)
df

                               text   emotion
0     I am feeling very happy today     happy
1      This is such a wonderful day     happy
2         I feel joyful and excited     happy
3                 Life is beautiful     happy
4                   I feel very sad       sad
5                This is depressing       sad
6                  I am heartbroken       sad
7            I feel lonely and down       sad
8         I am very angry right now     angry
9                 This makes me mad     angry
10                  I am frustrated     angry
11            I hate this situation     angry
12              I am scared of this      fear
13               This is terrifying      fear
14                   I feel nervous      fear
15  I am afraid of what will happen      fear
16           Wow this is surprising  surprise
17            I did not expect this  surprise
18                  This shocked me  surprise
19                      I am amazed  surprise
20               This is disgusting   disgust
21          I feel sick seeing this   disgust
22                    This is gross   disgust
23                I hate this smell   disgust
24               I love you so much      love
25                   This is lovely      love
26               I feel so attached      love
27        You mean everything to me      love
28                   I feel relaxed      calm
29                 This is peaceful      calm
30              I am calm and quiet      calm
31                   I feel at ease      calm

In [5]:
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]',' ', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df['clean_text'] = df['text'].apply(clean_text)
df

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                               text   emotion           clean_text
0     I am feeling very happy today     happy  feeling happy today
1      This is such a wonderful day     happy        wonderful day
2         I feel joyful and excited     happy  feel joyful excited
3                 Life is beautiful     happy       life beautiful
4                   I feel very sad       sad             feel sad
5                This is depressing       sad           depressing
6                  I am heartbroken       sad          heartbroken
7            I feel lonely and down       sad          feel lonely
8         I am very angry right now     angry          angry right
9                 This makes me mad     angry            makes mad
10                  I am frustrated     angry           frustrated
11            I hate this situation     angry       hate situation
12              I am scared of this      fear               scared
13               This is terrifying      fear           terrifying
14                   I feel nervous      fear         feel nervous
15  I am afraid of what will happen      fear        afraid happen
16           Wow this is surprising  surprise       wow surprising
17            I did not expect this  surprise               expect
18                  This shocked me  surprise              shocked
19                      I am amazed  surprise               amazed
20               This is disgusting   disgust           disgusting
21          I feel sick seeing this   disgust     feel sick seeing
22                    This is gross   disgust                gross
23                I hate this smell   disgust           hate smell
24               I love you so much      love            love much
25                   This is lovely      love               lovely
26               I feel so attached      love        feel attached
27        You mean everything to me      love      mean everything
28                   I feel relaxed      calm         feel relaxed
29                 This is peaceful      calm             peaceful
30              I am calm and quiet      calm           calm quiet
31                   I feel at ease      calm            feel ease

In [6]:
# Step 4: Tokenization & Padding

tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['clean_text'])    #number mapping for every word

X = tokenizer.texts_to_sequences(df['clean_text'])      #Ye line text ko numbers me convert karti hai
X = pad_sequences(X, maxlen=10)                            #Ye sab sequences ko same length ka banata hai maxlen = 10 => [0,0,0,0,0,0,0,2,3,1]

In [7]:
# Step 5: Label Encoding

encoder = LabelEncoder()
y = encoder.fit_transform(df['emotion'])

In [12]:

# Step 6: Build Model (Deep Learning)

model = Sequential()           # Simple stack model (layer by layer)
model.add(Embedding(input_dim=1000, output_dim=64, input_length=10))       #Ye words ko numbers → vectors me convert karta hai
model.add(LSTM(64))       # Ye sequence (sentence) ko samajhta hai (context) Example: "not good" vs "good" → LSTM difference samajh lega
model.add(Dense(32, activation='relu'))
model.add(Dense(8, activation='softmax'))   # ab multiple classes (3 ya usse zyada) ho Har class ki probability deta hai . Example output:[0.1, 0.7, 0.2]

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [13]:
# Step 7: Train Model

model.fit(X, y, epochs=20, batch_size=4, verbose=0)

Epoch 1/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.1250 - loss: 2.0836
Epoch 2/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1250 - loss: 2.0761
Epoch 3/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1250 - loss: 2.0711
Epoch 4/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1250 - loss: 2.0648
Epoch 5/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2500 - loss: 2.0558
Epoch 6/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2812 - loss: 2.0431
Epoch 7/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.2500 - loss: 2.0302
Epoch 8/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.2188 - loss: 2.0119
Epoch 9/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1875 - loss: 1.9832
Epoch 10/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3750 - loss: 1.9427
Epoch 11/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.2812 - loss: 1.8817
Epoch 12/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.3750 - loss: 1.8003
Epoch 13/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3125 - loss: 1.7251
Epoch 14/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3750 - loss: 1.6458
Epoch 15/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5938 - loss: 1.4238
Epoch 16/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6875 - loss: 1.2530
Epoch 17/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8438 - loss: 1.1269
Epoch 18/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9062 - loss: 0.9651
Epoch 19/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9062 - loss: 0.8322
Epoch 20/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.6591

In [14]:
# Step 8: Emotion Prediction Function

def predict_emotion(text):
    text = clean_text(text)
    seq = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(seq, maxlen=10)
    
    pred = model.predict(padded)
    emotion = encoder.inverse_transform([np.argmax(pred)])[0]
    
    return emotion

In [15]:
# Step 9: Take User Input

while True:
    user_input = input("\nEnter your sentence (type 'exit' to quit): ")
    
    if user_input.lower() == 'exit':
        print("Exiting Emotion Detector ")
        break
    
    emotion = predict_emotion(user_input)
    print(f"Detected Emotion: {emotion}")

Enter your sentence (type 'exit' to quit):  teri maa ka

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 426ms/step
Detected Emotion: surprise

Enter your sentence (type 'exit' to quit):  sex is good for health and gourav is sex worker

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
Detected Emotion: surprise

Enter your sentence (type 'exit' to quit):  exit

Exiting Emotion Detector